# Generated by Django 5.0 on 2025-09-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='coordenadas',
            field=models.JSONField(blank=True, help_text='Coordenadas en formato {"lat": float, "lng": float}', null=True),
        ),
    ]
