# Generated by Django 5.0 on 2025-09-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0002_alter_parcela_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='coordenadas',
            field=models.TextField(blank=True, help_text='Coordenadas en formato GeoJSON: {"type": "Point", "coordinates": [lng, lat]}', null=True),
        ),
    ]
