# Generated by Django 5.0 on 2025-09-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0003_alter_parcela_coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='parcela',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitud en grados decimales', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitud en grados decimales', max_digits=11, null=True),
        ),
    ]
