# Generated by Django 5.0 on 2025-09-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0004_remove_parcela_coordenadas_parcela_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraauditoria',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacoraauditoria',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('SESION_EXPIRADA', 'Sesión expirada'), ('SESION_INVALIDADA', 'Sesión invalidada'), ('BLOQUEO_CUENTA', 'Cuenta bloqueada'), ('DESBLOQUEO_CUENTA', 'Cuenta desbloqueada'), ('CAMBIAR_PASSWORD', 'Cambio de contraseña'), ('RESET_PASSWORD', 'Reset de contraseña'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('PERMISO_INSUFICIENTE', 'Permiso insuficiente')], max_length=50),
        ),
    ]
