# Generated by Django 5.0 on 2025-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0006_alter_bitacoraauditoria_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisissuelo',
            name='tipo_analisis',
            field=models.CharField(choices=[('QUIMICO', 'Químico'), ('FISICO', 'Físico'), ('BIOLOGICO', 'Biológico'), ('COMPLETO', 'Completo')], default='COMPLETO', help_text='Tipo de análisis realizado', max_length=20),
        ),
        migrations.AddField(
            model_name='cosecha',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado de la cosecha', max_length=20),
        ),
        migrations.AddField(
            model_name='transferenciaparcela',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', help_text='Estado de la transferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='transferenciaparcela',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraauditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FALLIDO', 'Intento de login fallido'), ('SESION_EXPIRADA', 'Sesión expirada'), ('SESION_INVALIDADA', 'Sesión invalidada'), ('BLOQUEO_CUENTA', 'Cuenta bloqueada'), ('DESBLOQUEO_CUENTA', 'Cuenta desbloqueada'), ('CAMBIAR_PASSWORD', 'Cambio de contraseña'), ('RESET_PASSWORD', 'Reset de contraseña'), ('ACCESO_DENEGADO', 'Acceso denegado'), ('PERMISO_INSUFICIENTE', 'Permiso insuficiente'), ('ACTIVAR_SOCIO', 'Activar socio'), ('DESACTIVAR_SOCIO', 'Desactivar socio'), ('ACTIVAR_USUARIO', 'Activar usuario'), ('DESACTIVAR_USUARIO', 'Desactivar usuario'), ('CREAR_CICLO_CULTIVO', 'Crear ciclo de cultivo'), ('ACTUALIZAR_CICLO_CULTIVO', 'Actualizar ciclo de cultivo'), ('CREAR_COSECHA', 'Crear cosecha'), ('ACTUALIZAR_COSECHA', 'Actualizar cosecha'), ('CREAR_TRATAMIENTO', 'Crear tratamiento'), ('ACTUALIZAR_TRATAMIENTO', 'Actualizar tratamiento'), ('CREAR_ANALISIS_SUELO', 'Crear análisis de suelo'), ('ACTUALIZAR_ANALISIS_SUELO', 'Actualizar análisis de suelo'), ('CREAR_TRANSFERENCIA_PARCELA', 'Crear transferencia de parcela'), ('ACTUALIZAR_TRANSFERENCIA_PARCELA', 'Actualizar transferencia de parcela'), ('PROCESAR_TRANSFERENCIA_APROBAR', 'Aprobar transferencia'), ('PROCESAR_TRANSFERENCIA_RECHAZAR', 'Rechazar transferencia')], max_length=50),
        ),
    ]
