# Generated by Django 5.0 on 2025-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperativa', '0007_analisissuelo_tipo_analisis_cosecha_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='es_sistema',
            field=models.BooleanField(default=False, help_text='Indica si es un rol del sistema que no puede ser eliminado'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(default=dict, help_text='Permisos del rol en formato JSON'),
        ),
    ]
